language: c
compiler:
    - clang
    - gcc
os:
    - linux
branches:
    only:
        - mpi
sudo: required
dist: trusty
notifications:
    email: false
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y \
      cmake \
      cmake-curses-gui \
      cmake-extras \
      extra-cmake-modules
script: mkdir build && cd build && cmake .. && make
